# Generated by Django 3.1.4 on 2020-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBPRI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Bolivia', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Uruguay', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Paraguay', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Venezuela', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Colombia', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Ecuador', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Peru', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Chile', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Argentina', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Mexico', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
