# Generated by Django 3.1.4 on 2020-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=5, verbose_name='2 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=5, verbose_name='3 Digit ISO'),
        ),
    ]
