# Generated by Django 3.1.4 on 2020-12-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201204_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='Country',
            new_name='name',
        ),
    ]
