# Generated by Django 3.1.4 on 2020-12-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_country_sbpri_worldborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
