# Generated by Django 3.1.4 on 2021-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210220_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbpri',
            name='Spain',
            field=models.DecimalField(blank=True, decimal_places=5, default='nan', max_digits=8, null=True),
        ),
    ]
