# Generated by Django 3.1.4 on 2021-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='capital',
            field=models.CharField(default='still missing', max_length=30),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='continent',
            field=models.CharField(choices=[('south america', 'south america'), ('north america', 'north america'), ('europe', 'europe'), ('africa', 'africa'), ('asia', 'asia'), ('world', 'world')], default='world', max_length=30),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='ctryimg',
            field=models.ImageField(default='worldmap_02.png', upload_to='ctryimg'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='currency',
            field=models.CharField(default='still missing', max_length=10),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='flag',
            field=models.ImageField(default='worldmap_02.png', upload_to='flags'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='language',
            field=models.CharField(default='still missing', max_length=30),
        ),
    ]
