# Generated by Django 3.1.4 on 2021-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='worldmap_02.png', upload_to='post_pics'),
        ),
    ]
